spring:
  application:
    name: users

server:
  port: 8200

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true

security:
  cognito:
    userPoolId: eu-central-1_swSI22YKe

rabbit: amqp://teupkmiz:Wk14xnvmqU1jW3eZYGtUSwcgFjU_jGWg@barnacle.rmq.cloudamqp.com/teupkmiz